### PR TITLE
Create a diversion mechanism to load different modules based on theme version

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Hey @Robert-Frampton , this PR is failing in node6 in travis, but correctly working in local. Also, a previous PR worked in node6 so I think the race conditions are happening in Travis too.

Any hint?

**Comment by Robert-Frampton** [comment]
Hey @izaera not sure exactly, but just to rule it out, I sent https://github.com/liferay/liferay-theme-tasks/pull/68 that updates the version of the test runner to see if that resolves anything. I also updated to the latest release of Node 6.x.

**Comment by Robert-Frampton** [comment]
Looks like it worked! I'll go ahead and close this PR in favor of #68

**Pull request closed without merging**
