### PR TITLE
setup watching of UI files outside of the standard Liferay theme dire…

### PR DESCRIPTION
**Pull request by croucha**
…ctory stucture

### CODE REVIEW

**Comment by croucha** [comment]
Currently, this watcher doesn't monitor single UI files changes to css, js and images outside of the standard Liferay directory structure.  I have modified it so it will do both.

**Comment by croucha** [comment]
I noticed some checks failed here?  Is there something I need to do to help with this?

**Comment by jbalsas** [comment]
Hey @croucha, thanks for the contribution! We will move this PR to https://github.com/liferay/liferay-themes-sdk, which is where we're trying to consolidate all theme tooling, but for now I'd like to continue the conversation here.

Can you explain what's your use case with some more detail? We'd like to fully understand it so we can figure out the best general solution for it.

Thanks!

**Comment by croucha** [comment]
Hi @jbalsas! Basically I was hoping to have some way for ['deploy:file'] to execute if it detected a JS/CSS/image change outside of src/js/, src/css, src/images.  I have a use case were I was storing these assets in a folder like src/portletAssets/portlet1/js/,  src/portletAssets/portlet1/css/,  src/portletAssets/portlet1/images and it doesn't seem to run ['deploy:file'] when making a change. 

Thanks!

**Comment by jbalsas** [comment]
Hey @croucha, sorry for the delay, I've opened https://github.com/liferay/liferay-themes-sdk/issues/28 and we'll be taking a look at this next!

**Pull request closed without merging**
