### PR TITLE
Proposed solution to issue #87 gulp extend published npm themelet not working

### PR DESCRIPTION
**Pull request by paulocfjunior**
This PR wants to solve #87. There were some validations missing in case of packages with multiple versions, and one dependency had to be upgraded.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @paulocfjunior, sorry I missed this!

As I mentioned, we've moved all current development to https://github.com/liferay/liferay-themes-sdk

Would you mind sending this over there over the current code? (`develop` branch).

We're in the process of signaling this as deprecated and archiving it, sorry for the inconvenience! :(

**Comment by paulocfjunior** [comment]
Hi @jbalsas, no problem, I updated to 8.0.0-beta.1 and seems all were fixed.

**Comment by jbalsas** [comment]
Cool, are you sure? I don't remember making similar changes in upstream... please, file any additional issue you find on the other repo and we'll take a look.

Thanks for contributing @paulocfjunior!

**Comment by paulocfjunior** [comment]
Yeah @jbalsas, actually today I was trying to do some 'extends' and realize my packages weren't appearing. I thought it was my fault, but it wasn't. The npm-keywords dependency is not working as we expected, it doesn't return all the packages, nor in the npm site. I'll submit a PR on the SDK repo with a possible solution for that.

**Pull request closed without merging**
